# Generated by Django 4.2.26 on 2025-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_sharednote_studysession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homework",
            name="due",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="homework",
            name="subject",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="homework",
            name="title",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="notes",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="sharednote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="sharednote",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="subject",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
